# Generated by Django 4.2.4 on 2023-08-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
